# Generated by Django 3.2.16 on 2022-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0003_createpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
