# Generated by Django 3.2.16 on 2022-12-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0005_alter_createpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_blog_details', to='blogapi.createpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_user_details', to='blogapi.bloguser')),
            ],
            options={
                'verbose_name': 'Logger',
                'verbose_name_plural': 'Loggers',
            },
        ),
    ]
