# Generated by Django 3.2.16 on 2022-12-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0006_logger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='blog',
            new_name='blog_log',
        ),
        migrations.RenameField(
            model_name='logger',
            old_name='user',
            new_name='user_log',
        ),
    ]
