# Generated by Django 3.2.16 on 2022-12-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0007_auto_20221210_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='blog_log',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='logger',
            old_name='user_log',
            new_name='user',
        ),
    ]
