# Generated by Django 3.2.16 on 2022-12-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0010_auto_20221210_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('hit_count', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'CountHistory',
                'verbose_name_plural': 'CountHistorys',
            },
        ),
    ]
