# Generated by Django 3.2.16 on 2022-12-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0011_counthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='counthistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='counthistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='createpost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='createpost',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='logger',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='logger',
            name='updated_by',
        ),
    ]
