# Generated by Django 3.2.16 on 2022-12-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0012_auto_20221210_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='counthistory',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_hit_details', to='blogapi.bloguser'),
            preserve_default=False,
        ),
    ]
